@baseUrl = http://localhost:4001/api/v1

### Login
# @name loginUser
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "password123"
}