@baseUrl = http://localhost:4001/api/v1

### Refresh Token
# @name refreshToken
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTllODk0OC1hYTM4LTc1YWEtOTY3My02NDliNmU4MGQ2OTAiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJpYXQiOjE3ODA0MTk3MTMsImV4cCI6MTc4MzAxMTcxM30.G7P6RCRQXJRcxU8BPCd6HvCv-IVtsvS55zM437uY1co"
}
